### ISSUE TITLE
Update Temp voice

### ISSUE THREAD

**Issue by The-Tasty-Jaffa** [The-Tasty-Jaffa/Tasty-Jaffa-cogs#30]
- [x] Make help more helpful
- [x] Rename it to `tempvoice` rather than the current  #`TempVoice`
- [x] Move new channel underneath the "lobby" channel
- [x] Move channel into category
- [x] Rate limit channel creation (case#28)

**Comment by The-Tasty-Jaffa** [comment]
There is (always has been) move_channel(channel, position) but I have been having issues with that (categories seem to be interfering with it)

**Comment by KensonPlays** [comment]
Could it be possible to have it only show in a certain category?

**Comment by The-Tasty-Jaffa** [comment]
It should be possible. This should be possible if I where to send JSON to the right address with the right info (effectively it's own API) . I don't know when about it will be coming other than it's planned!

**Comment by KensonPlays** [comment]
The sooner, the better ;)

I can't really use it until then.

**Comment by The-Tasty-Jaffa** [comment]
Made PR that adds Category implementation for tempvoice.
If there are any issues with the changes please make a new issue detailing the problem. (I have tested it and not found any issues yet)
