### ISSUE TITLE
Add a random text cog

### ISSUE THREAD

**Issue by eaten-squid** [The-Tasty-Jaffa/Tasty-Jaffa-cogs#39]
Hey, I have some cogs in a different repo, thought you might want to add them to here. They're not much.

I suggest the cogs -
- randtext (responds with random text)
- register (for registration of people to the server but this needs some work... I'll make a different issue for that)

- Thanks, Eaten Squid

**Comment by The-Tasty-Jaffa** [comment]
I will have a look.
