### ISSUE TITLE
[Suggestion] Temp Room to make it better

### ISSUE THREAD

**Issue by BarterClub** [The-Tasty-Jaffa/Tasty-Jaffa-cogs#44]
So ive been looking around for an bot that can make rooms when the person clicks on a voice channel. https://discord.gg/escape-from-tarkov does a nice job with this. The issue with yours is that you cant have custom names: user name, game, or something else. The other issue is that you cant have a private channel either. Those are some features that would be cool that were added to yours. 

- Private Room and only can get invited in by link. 
- Ability to have name change to having their name or something else.

**Comment by The-Tasty-Jaffa** [comment]
In the current version it is possible to set a default name for created
channels (see `setvoice` and its subcommand `name`). It is also possible
for the person who created the channel as well as mods to change the name
of the channel too!
Currently in this version (for red v2) it is not possible to have a private
room. However, it should be noted that this is a planned feature for the V3
release.

**Comment by The-Tasty-Jaffa** [comment]
In the current version it is possible to set a default name for created channels (see `setvoice` and its subcommand `name`). It is also possible for the person who created the channel as well as mods to change the name of the channel too! Currently in this version (for red v2) it is not possible to have a private room. However, it should be noted that this is a planned feature for the V3 release.

**Comment by BarterClub** [comment]
Right if you want them to use commands. Im trying to not use commands for anything. So when person clicks on a channel they get moved to a new one with name of channel being what its called with there name and how many people are allowed.

**Comment by The-Tasty-Jaffa** [comment]
Ah, The person who created the channel has the right specific channel perms to modify the maximum number of people and also change the name of the channel when they edit the channel using discords UI.

The previously mentioned command simply changes the default name that will be used when a channel is created... for example if using the command to set it as `"{user.nick} is playing {user.game}"` and I was to join the right channel to create a new, temporary channel while playing say Fortnite then the channel would read `The Tasty Jaffa is playing Fortnite` when it is created... I would, however, still be able to change it *without* using any commands and just though the Discord UI.

**Comment by BarterClub** [comment]
Ok thanks. Is there a way so it copy's how many people can join the channel? As in if i have the channel only allow 4 people in it, it will make a copy of 4 people only in the new temp channel.

**Comment by BarterClub** [comment]
So i was looking at your code, these are what i was noticing. There is no user_limit to no know if the new channel should be just 3 people or whatever. There is no way to have more than one json file that has the settings. As in you cant have more than one channel at a time with different settings.

**Comment by The-Tasty-Jaffa** [comment]
Settings user limits is done solely though the discord UI (using channel settings)

Copying the user limit is not something that the v2 release does but should be available in the v3 release.
Where as having multiple channels is something that I will consider for a later v3 release.

Finally I am closing this issue because `Private Room and only can get invited in by link.` is a discord group chat feature that should arrive at some point and `Ability to have name change to having their name or something else.` (so user limit etc is already featured and will be more detailed in a coming planned update/release for v3). However do feel free to create a new issue for having more than one channel for creating temporary channels.
