### ISSUE TITLE
Can't install cog

### ISSUE THREAD

**Issue by Chriskm2001** [The-Tasty-Jaffa/Tasty-Jaffa-cogs#46]
Hello, I can't install cog as it says rolenotifier can't be found in the repo

**Comment by The-Tasty-Jaffa** [comment]
Hi! This repo currently only works for Red V2 and was only upgraded for V3 beta (Current version 3.4.18) on a Gitlab repo.

There have been lots, probably breaking changes over 4 years ;/

I can look into this further if the problem persists. For now, I would suggest looking at this [Repo for Red V3 rc1](https://gitlab.com/The_Tasty_Jaffa/Tasty-Jaffa-cogs/-/tree/v3/release) The Cog you're asking about was renamed to RoleAlert.

lmk how you get on :)

**Comment by Chriskm2001** [comment]
![Screenshot_20220908-210538~2](https://user-images.githubusercontent.com/112778174/189205841-da9d1821-e655-496f-be2e-93b088a17934.png)

**Comment by The-Tasty-Jaffa** [comment]
Thank you for sending a screenshot. Could you show me the output of `!info` and error logs when running the command?

**Comment by The-Tasty-Jaffa** [comment]
@Chriskm2001 Issue has been fixed. Try updating the repo.
Thanks for using this project and bringing this to my attention :)
